package com.cyberflux.qwinai

import android.view.View
import android.widget.TextView
import androidx.recyclerview.widget.RecyclerView
import androidx.viewbinding.ViewBinding

/**
 * Manual view binding class for fragment_home.xml
 * In a real project, this would be auto-generated by the ViewBinding system
 */
class FragmentHomeBinding private constructor(
    private val rootView: View
) : ViewBinding {

    val featuresTitle: TextView = rootView.findViewById(R.id.featuresTitle)
    val featuresRecyclerView: RecyclerView = rootView.findViewById(R.id.featuresRecyclerView)
    val promptsTitle: TextView = rootView.findViewById(R.id.promptsTitle)

    override fun getRoot(): View = rootView

    companion object {
        fun inflate(
            inflater: android.view.LayoutInflater,
            parent: android.view.ViewGroup?,
            attachToParent: Boolean
        ): FragmentHomeBinding {
            val root = inflater.inflate(R.layout.fragment_home, parent, false)
            if (attachToParent) {
                parent?.addView(root)
            }
            return FragmentHomeBinding(root)
        }
    }
}